-- ============================================
-- COINS TABLE
-- Bitta tanga (Result ekrandagi barcha ma'lumotlar)
-- ============================================
CREATE TABLE public.coins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- Identifikatsiya
  name TEXT NOT NULL,
  country TEXT NOT NULL,
  year_start INTEGER,
  year_end INTEGER,
  front_image_url TEXT,
  back_image_url TEXT,

  -- Qisqacha (kartochkalar)
  mintage BIGINT,
  composition TEXT,

  -- Narx va grading
  estimated_price_min NUMERIC(10, 2),
  estimated_price_max NUMERIC(10, 2),
  grade_label TEXT,
  grade_value INTEGER,

  -- Specifications (Details tab)
  denomination TEXT,
  metal_composition_detailed TEXT,
  weight_grams NUMERIC(10, 2),
  diameter_mm NUMERIC(10, 2),
  thickness_mm NUMERIC(10, 2),
  edge_type TEXT,

  -- History & AI
  designer TEXT,
  history_description TEXT,
  ai_opinion TEXT,
  dimension_illustration_url TEXT
);

-- ============================================
-- COLLECTIONS TABLE
-- Foydalanuvchi kolleksiyasi, faqat coin id lar
-- ============================================
CREATE TABLE public.collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,

  -- Tanga id lari (int8 = BIGINT)
  coin_ids BIGINT[] DEFAULT '{}' NOT NULL
);

CREATE INDEX collections_user_id_idx ON public.collections (user_id);

-- ============================================
-- RLS (Row Level Security)
-- ============================================
ALTER TABLE public.coins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

-- coins: barcha autentifikatsiyadan o'tganlar o'qiy oladi
CREATE POLICY "coins_select" ON public.coins
  FOR SELECT TO authenticated USING (true);

-- collections: faqat o'zining kolleksiyasini ko'radi/o'zgartiradi
CREATE POLICY "collections_select" ON public.collections
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "collections_insert" ON public.collections
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "collections_update" ON public.collections
  FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "collections_delete" ON public.collections
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
