-- ============================================
-- BLOG POSTS TABLE
-- Home pagedagi "Collectors Blog" kartalari uchun
-- ============================================
CREATE TABLE public.blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  title TEXT NOT NULL,
  thumbnail_url TEXT,
  read_time_minutes INTEGER NOT NULL DEFAULT 0,
  excerpt TEXT,
  url TEXT,

  sort_order INTEGER DEFAULT 0
);

-- Home da chiqish tartibi
CREATE INDEX blog_posts_sort_order_idx ON public.blog_posts (sort_order, created_at DESC);

-- ============================================
-- RLS
-- ============================================
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Barcha (hatto login qilmagan) o'qiy oladi
CREATE POLICY "blog_posts_select" ON public.blog_posts
  FOR SELECT TO anon, authenticated USING (true);

-- Yozish faqat service role yoki keyingi qadamda admin uchun qo'shasiz
-- CREATE POLICY "blog_posts_insert" ON public.blog_posts ...
