-- ============================================
-- BLOG CATEGORIES
-- ============================================
CREATE TABLE public.blog_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0
);

CREATE INDEX blog_categories_sort_order_idx ON public.blog_categories (sort_order, id);

ALTER TABLE public.blog_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "blog_categories_select" ON public.blog_categories
  FOR SELECT TO anon, authenticated USING (true);

-- ============================================
-- blog_posts ga category_id
-- ============================================
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.blog_categories(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS blog_posts_category_id_idx ON public.blog_posts (category_id);

-- Namuna kategoriyalar (migration bir marta ishlaganda)
INSERT INTO public.blog_categories (name, sort_order)
SELECT 'Analyzing', 1
WHERE NOT EXISTS (SELECT 1 FROM public.blog_categories WHERE name = 'Analyzing');
INSERT INTO public.blog_categories (name, sort_order)
SELECT 'News', 2
WHERE NOT EXISTS (SELECT 1 FROM public.blog_categories WHERE name = 'News');
INSERT INTO public.blog_categories (name, sort_order)
SELECT 'Latest Posts', 3
WHERE NOT EXISTS (SELECT 1 FROM public.blog_categories WHERE name = 'Latest Posts');
