-- ============================================
-- COMMUNITY POSTS
-- ============================================
CREATE TABLE public.community_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  image_urls TEXT[] DEFAULT '{}' NOT NULL
);

CREATE INDEX community_posts_user_id_idx ON public.community_posts (user_id);
CREATE INDEX community_posts_created_at_idx ON public.community_posts (created_at DESC);

-- ============================================
-- COMMUNITY POST LIKES
-- ============================================
CREATE TABLE public.community_post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,

  UNIQUE (post_id, user_id)
);

CREATE INDEX community_post_likes_post_id_idx ON public.community_post_likes (post_id);
CREATE INDEX community_post_likes_user_id_idx ON public.community_post_likes (user_id);

-- ============================================
-- COMMUNITY REPLIES
-- ============================================
CREATE TABLE public.community_replies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL
);

CREATE INDEX community_replies_post_id_idx ON public.community_replies (post_id);
CREATE INDEX community_replies_user_id_idx ON public.community_replies (user_id);
CREATE INDEX community_replies_created_at_idx ON public.community_replies (created_at ASC);

-- ============================================
-- COMMUNITY REPLY LIKES
-- ============================================
CREATE TABLE public.community_reply_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  reply_id BIGINT REFERENCES public.community_replies(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,

  UNIQUE (reply_id, user_id)
);

CREATE INDEX community_reply_likes_reply_id_idx ON public.community_reply_likes (reply_id);
CREATE INDEX community_reply_likes_user_id_idx ON public.community_reply_likes (user_id);

-- ============================================
-- RLS
-- ============================================
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_reply_likes ENABLE ROW LEVEL SECURITY;

-- Posts: barcha authenticated o'qiy oladi
CREATE POLICY "community_posts_select" ON public.community_posts
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "community_posts_insert" ON public.community_posts
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "community_posts_update" ON public.community_posts
  FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "community_posts_delete" ON public.community_posts
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Post Likes
CREATE POLICY "community_post_likes_select" ON public.community_post_likes
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "community_post_likes_insert" ON public.community_post_likes
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "community_post_likes_delete" ON public.community_post_likes
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Replies
CREATE POLICY "community_replies_select" ON public.community_replies
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "community_replies_insert" ON public.community_replies
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "community_replies_update" ON public.community_replies
  FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "community_replies_delete" ON public.community_replies
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Reply Likes
CREATE POLICY "community_reply_likes_select" ON public.community_reply_likes
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "community_reply_likes_insert" ON public.community_reply_likes
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "community_reply_likes_delete" ON public.community_reply_likes
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
